#!.venv/bin/python

import aspose.words as aw
from sys import argv, exit, stderr

ARGV = argv[1:]

try:
    aw.Document(ARGV[0]).save(ARGV[1])
except BaseException as e:
    print(e, file=stderr)
    exit(1)
