#!.venv/bin/python
import sys

from App import Application

if not Application(Application.ApplicationType.Server):
    sys.exit(1)

from App import helpers


def main():
    helpers.start_server()


if __name__ == "__main__":
    main()
